# Generated by Django 4.1 on 2022-08-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belka_app', '0002_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nut',
        ),
        migrations.AddField(
            model_name='photo',
            name='priority',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
