# Generated by Django 4.0.5 on 2022-11-20 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('thumbnail', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
