# Generated by Django 4.0.5 on 2022-09-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belka_app', '0003_delete_nut_photo_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
